# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
  - script: wget -qO- --retry-connrefused https://storage.googleapis.com/matlabimagesus/public/install.sh | sudo -E bash
  - script: matlab -batch "disp('Hello World')"
  - script: matlab -batch "cd Software/MATLAB"
  - script: matlab -batch "startup"
  - script: matlab -batch "disp('Running Unit Tests')"
  - script: matlab -batch "cd test/unit"
  - script: matlab -batch "runtests"